CT-195 Send serverHost as __origServerHost
scalyr/kafka-connect-scalyr pull request #33
Opened 2020-10-10 05:14 UTC by oliverhsu77

To match the server changes for CT-195:
1. Send `serverHost` as `__origServerHost` `logs` add events attribute.
2. Remove sending `serverHost` as `origin`.

This should not be merged until after CT-195 server changes are merged.

2020-10-13 20:47 UTC, czerwingithub requested changes

2020-10-13 20:47 UTC, czerwingithub commented on src/main/java/com/scalyr/integrations/kafka/AddEventsClient.java
> +      // __origServerHost event attr will be promoted to serverHost session attr
I would say `__origServerHost event attr will be promoted to serverHost session attr on the server`.

2020-10-13 20:47 UTC, czerwingithub commented on src/test/java/com/scalyr/integrations/kafka/AddEventsClientTest.java
> +  private static final String SERVERHOST = "__origServerHost";
Let's rename the variable to `ORIG_SERVERHOST` just for clarity.

2020-10-13 23:41 UTC, oliverhsu77 commented
Addressed review comments.  Ready for another look.  Thanks!

2020-10-14 16:05 UTC, czerwingithub approved these changes

2020-10-23 17:25 UTC, merged